### 일상 [0,1,0] 레이블 데이터

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("./angle_data/daily/DDA_In_MIX_00385.csv")
df = df.drop(['Unnamed: 0'],axis=1)
input1 = df.values
input1.shape

(90, 4)

In [3]:
data_targets=[]

In [4]:
#arr1 = np.ones((90,4))
arrays=[]
for direc in os.listdir("./angle_data/daily"):
    df = pd.read_csv("./angle_data/daily/{}".format(direc))
    df = df.drop(['Unnamed: 0'],axis=1)
    input1 = df.values
    arrays.append(input1)
    #arr1 = np.stack((arr1,df.values))
    print(input1.shape)

(90, 4)
(90, 4)
(105, 4)
(87, 4)
(86, 4)
(86, 4)
(89, 4)
(90, 4)
(30, 4)
(90, 4)
(29, 4)
(76, 4)
(90, 4)
(116, 4)
(90, 4)
(24, 4)
(89, 4)
(90, 4)
(89, 4)
(90, 4)
(73, 4)
(53, 4)
(91, 4)
(83, 4)
(61, 4)
(137, 4)
(118, 4)
(90, 4)
(90, 4)
(90, 4)
(90, 4)
(90, 4)
(90, 4)
(58, 4)
(89, 4)
(90, 4)


In [5]:
# 배열을 (30, 4)의 shape로 분할하고 패딩
padded_arrays = []
for array in arrays:
    num_segments = array.shape[0] // 30
    remainder = array.shape[0] % 30
    
    if num_segments > 0:
        # (30, 4)로 분할
        segments = np.split(array[:num_segments*30], num_segments)
        padded_arrays.extend(segments)
    
    if remainder > 0:
        # 패딩된 (30, 4) 추가
        padding = np.tile(array[-1], (30 - remainder, 1))
        padded_array = np.concatenate([array[-remainder:], padding], axis=0)
        padded_arrays.append(padded_array)

# 결과 출력
for padded_array in padded_arrays:
    print(padded_array.shape)

(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)


In [6]:
print(len(padded_arrays))

106


In [7]:
# 분할된 input array 길이 측정
len_arr = len(padded_arrays)
len_arr
# target data 생성
tar_arr2 = []
for _ in range(len_arr):
    tar_arr2.append([0,1,0])
len(tar_arr2)

106

In [8]:
for data,tar in zip(padded_arrays,tar_arr2):
    data_targets.append((data,tar))

### 배회 [0,0,1] 레이블 데이터

In [9]:
df = pd.read_csv("./angle_data/walking/WD_In_W11W24_0019_20201125_14.csv")
df = df.drop(['Unnamed: 0'],axis=1)
input1 = df.values
input1.shape

(180, 4)

In [10]:
#arr1 = np.ones((90,4))
arrays2=[]
for direc in os.listdir("./angle_data/walking"):
    df2 = pd.read_csv("./angle_data/walking/{}".format(direc))
    df2 = df2.drop(['Unnamed: 0'],axis=1)
    input2 = df2.values
    arrays2.append(input2)
    #arr1 = np.stack((arr1,df.values))
    print(input2.shape)

(180, 4)
(180, 4)
(90, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(179, 4)
(91, 4)
(90, 4)
(180, 4)
(180, 4)
(178, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)
(180, 4)


In [11]:
# 배열을 (30, 4)의 shape로 분할하고 패딩
padded_arrays2 = []
for array in arrays2:
    num_segments = array.shape[0] // 30
    remainder = array.shape[0] % 30
    
    if num_segments > 0:
        # (30, 4)로 분할
        segments = np.split(array[:num_segments*30], num_segments)
        padded_arrays2.extend(segments)
    
    if remainder > 0:
        # 패딩된 (30, 4) 추가
        padding = np.tile(array[-1], (30 - remainder, 1))
        padded_array = np.concatenate([array[-remainder:], padding], axis=0)
        padded_arrays2.append(padded_array)

# 결과 출력
for padded_array in padded_arrays2:
    print(padded_array.shape)

(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)


In [12]:
len(padded_arrays2)

196

In [13]:
# 분할된 input array 길이 측정
len_arr2 = len(padded_arrays2)
len_arr2
# target data 생성
tar_arr_walk = []
for _ in range(len_arr2):
    tar_arr_walk.append([0,0,1])
tar_arr_walk

[[0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0, 0, 1],
 [0,

In [14]:
for data,tar in zip(padded_arrays2,tar_arr_walk):
    data_targets.append((data,tar))

### 낙상 [1,0,0] 레이블 데이터

In [15]:
df = pd.read_csv("./angle_data/falling/FD_In_H11H21H31_0009_20201229_14.csv")
df = df.drop(['Unnamed: 0'],axis=1)
input3 = df.values
input3.shape

(58, 4)

In [16]:
#arr1 = np.ones((90,4))
arrays3=[]
for direc in os.listdir("./angle_data/falling"):
    df3 = pd.read_csv("./angle_data/falling/{}".format(direc))
    df3 = df3.drop(['Unnamed: 0'],axis=1)
    input3 = df3.values
    arrays3.append(input3)
    #arr1 = np.stack((arr1,df.values))
    print(input3.shape)

(58, 4)
(20, 4)
(46, 4)
(22, 4)
(60, 4)
(52, 4)
(42, 4)
(55, 4)
(88, 4)
(11, 4)
(48, 4)
(30, 4)
(60, 4)
(15, 4)
(23, 4)
(39, 4)
(24, 4)
(10, 4)
(59, 4)
(23, 4)
(9, 4)
(23, 4)
(26, 4)
(14, 4)
(13, 4)
(21, 4)
(14, 4)
(31, 4)
(12, 4)
(30, 4)
(45, 4)
(47, 4)
(31, 4)
(45, 4)
(22, 4)
(22, 4)
(29, 4)
(36, 4)
(18, 4)
(20, 4)
(17, 4)
(60, 4)
(31, 4)
(40, 4)
(52, 4)
(45, 4)
(23, 4)
(17, 4)
(48, 4)
(48, 4)
(7, 4)
(7, 4)


In [17]:
# 배열을 (30, 4)의 shape로 분할하고 패딩
padded_arrays3 = []
for array in arrays3:
    num_segments = array.shape[0] // 30
    remainder = array.shape[0] % 30
    
    if num_segments > 0:
        # (30, 4)로 분할
        segments = np.split(array[:num_segments*30], num_segments)
        padded_arrays3.extend(segments)
    
    if remainder > 0 and array.shape[0] > 10:
        # 잘랐을 때 길이가 10이하인 데이터는 삭제
        # 패딩된 (30, 4) 추가
        padding = np.tile(array[-1], (30 - remainder, 1))
        padded_array = np.concatenate([array[-remainder:], padding], axis=0)
        padded_arrays3.append(padded_array)

# 결과 출력
for padded_array in padded_arrays3:
    print(padded_array.shape)

(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)
(30, 4)


In [18]:
# 분할된 input array 길이 측정
len_arr3 = len(padded_arrays3)
# target data 생성
tar_arr_fall = []
for _ in range(len_arr3):
    tar_arr_fall.append([1,0,0])
tar_arr_fall

[[1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0],
 [1, 0, 0]]

In [19]:
for data,tar in zip(padded_arrays3,tar_arr_fall):
    data_targets.append((data,tar))

In [20]:
len(data_targets)

375

### 데이터의 shape를 (30,4)에서 (5,4)로 변환
### (웹에서 캡쳐하는 프레임의 한계 때문)

In [21]:
reshaped_data = []

for i in range(len(data_targets)):
    group = data_targets[i][0]
    reshaped_group = group.reshape((5,6,4))
    mean_values = np.mean(reshaped_group, axis=1)
    reshaped_data.append((mean_values,data_targets[i][1]))
print(reshaped_data)

[(array([[154.64693479,  45.09724843, 115.67320047, 134.66008736],
       [161.20257872,  45.52296002, 132.20260433, 162.00990514],
       [167.55257548,  44.21090473, 137.216009  , 157.44158368],
       [172.90048955,  41.41074372, 128.07949464, 150.39762072],
       [155.08066484,  42.57125484, 128.6410104 , 143.29621697]]), [0, 1, 0]), (array([[164.86521382,  35.85131162,  90.58647326, 100.58055684],
       [165.46766068,  37.768573  , 158.67123066, 149.24670215],
       [168.42883205,  42.79882832, 135.41372112, 113.90264442],
       [171.54501538,  40.88443031, 142.45828269, 124.0193357 ],
       [164.45217035,  42.72938146, 119.39960738,  93.98480042]]), [0, 1, 0]), (array([[168.11842699,  43.41520128, 122.40808363, 121.41604821],
       [166.7917022 ,  43.18922772, 134.08290093, 132.12618801],
       [177.83238963,  38.54625997, 157.15833768, 159.22077028],
       [178.03931955,  38.44057778, 153.46134992, 168.16688768],
       [176.19977256,  39.91058651, 160.98060242, 169.9151

       [131.50835046,   2.53251842, 128.43753812, 138.07275962]]), [1, 0, 0])]


In [22]:
print(len(reshaped_data))
data_targets=reshaped_data

375


### 데이터 증강

In [23]:
import numpy as np
import random

# 데이터 증강 함수 정의
def augment_data(data, target, num_samples):
    augmented_data = []
    augmented_target = []
    
    for _ in range(num_samples):
        # 데이터 회전
        angle = random.uniform(0, 360)
        rotated_data = np.apply_along_axis(lambda x: np.roll(x, int(angle)), axis=0, arr=data)
        augmented_data.append(rotated_data)
        augmented_target.append(target)
        
        # 노이즈 추가
        noise = np.random.normal(0, 0.1, size=data.shape)
        noisy_data = data + noise
        augmented_data.append(noisy_data)
        augmented_target.append(target)
        
        # 시간 이동
        shift = random.randint(1, data.shape[0] - 1)
        shifted_data = np.roll(data, shift, axis=0)
        augmented_data.append(shifted_data)
        augmented_target.append(target)
        
        # 스케일 조정
        scale_factor = random.uniform(0.8, 1.2)
        scaled_data = data * scale_factor
        augmented_data.append(scaled_data)
        augmented_target.append(target)
    
    augmented_data = np.array(augmented_data)
    augmented_target = np.array(augmented_target)
    
    return augmented_data, augmented_target

# 데이터 증강 수행
num_samples = 10  # 추가할 데이터 샘플 수

augmented_data_targets = []
for data, target in data_targets:
    augmented_data, augmented_target = augment_data(data, target, num_samples)
    augmented_data_targets.extend(zip(augmented_data, augmented_target))

# 증강된 데이터 확인
print("원본 데이터 개수:", len(data_targets))
print("증강된 데이터 개수:", len(augmented_data_targets))

원본 데이터 개수: 375
증강된 데이터 개수: 15000


In [24]:
data_targets = augmented_data_targets
data_targets

[(array([[155.08066484,  42.57125484, 128.6410104 , 143.29621697],
         [154.64693479,  45.09724843, 115.67320047, 134.66008736],
         [161.20257872,  45.52296002, 132.20260433, 162.00990514],
         [167.55257548,  44.21090473, 137.216009  , 157.44158368],
         [172.90048955,  41.41074372, 128.07949464, 150.39762072]]),
  array([0, 1, 0])),
 (array([[154.72556962,  44.90707963, 115.5391974 , 134.72112994],
         [161.19563939,  45.51439968, 132.20557477, 162.2265033 ],
         [167.58556326,  44.10551049, 137.42280944, 157.47256456],
         [172.85532342,  41.42861997, 127.96874482, 150.56961402],
         [155.0167953 ,  42.42566508, 128.63253483, 143.17288445]]),
  array([0, 1, 0])),
 (array([[172.90048955,  41.41074372, 128.07949464, 150.39762072],
         [155.08066484,  42.57125484, 128.6410104 , 143.29621697],
         [154.64693479,  45.09724843, 115.67320047, 134.66008736],
         [161.20257872,  45.52296002, 132.20260433, 162.00990514],
         [167.55

### 데이터 분할

In [25]:
import random

# 전체 데이터를 훈련 및 검증 데이터로 분할하기 위한 비율
train_ratio = 0.8

# 데이터와 클래스(타겟) 쌍을 훈련 및 검증 데이터로 분할
random.shuffle(data_targets)  # 데이터 순서를 무작위로 섞음

# 분할 지점 계산
split_point = int(len(data_targets) * train_ratio)

# 훈련 데이터와 검증 데이터로 분할
train_data_targets = data_targets[:split_point]
val_data_targets = data_targets[split_point:]

In [26]:
len(train_data_targets)

12000

In [27]:
len(val_data_targets)

3000

### 모델 생성

In [28]:
from tensorflow import keras
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np

# LSTM 모델 구성
model = keras.Sequential()
model.add(keras.layers.LSTM(units=128, input_shape=(5, 4), return_sequences=True))
model.add(keras.layers.Dropout(0.2))  # Dropout 추가
model.add(keras.layers.LSTM(units=128))
model.add(keras.layers.Dropout(0.2))  # Dropout 추가
model.add(keras.layers.Dense(units=64, activation='relu', kernel_regularizer=keras.regularizers.l2(0.01)))  # Regularization 추가
model.add(keras.layers.Dense(units=3, activation='softmax'))

# 모델 컴파일
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# 데이터 전처리: 데이터와 클래스(타겟) 분리
train_data, train_targets = zip(*train_data_targets)
val_data, val_targets = zip(*val_data_targets)

# 데이터 전처리: numpy 배열로 변환
train_data = np.array(train_data)
train_targets = np.array(train_targets)
val_data = np.array(val_data)
val_targets = np.array(val_targets)

early_stopping = EarlyStopping(patience=10, restore_best_weights=True)

# 모델 학습
model.fit(train_data, train_targets, validation_data=(val_data, val_targets),
          epochs=100, batch_size=32, callbacks=[early_stopping])

Epoch 1/100
375/375 [==============================] - 5s 7ms/step - loss: 0.7628 - accuracy: 0.7909 - val_loss: 0.4898 - val_accuracy: 0.8253
Epoch 2/100
375/375 [==============================] - 2s 6ms/step - loss: 0.4357 - accuracy: 0.8397 - val_loss: 0.3761 - val_accuracy: 0.8567
Epoch 3/100
375/375 [==============================] - 2s 5ms/step - loss: 0.3622 - accuracy: 0.8585 - val_loss: 0.3833 - val_accuracy: 0.8050
Epoch 4/100
375/375 [==============================] - 2s 5ms/step - loss: 0.3265 - accuracy: 0.8688 - val_loss: 0.2738 - val_accuracy: 0.8977
Epoch 5/100
375/375 [==============================] - 2s 5ms/step - loss: 0.2978 - accuracy: 0.8778 - val_loss: 0.2366 - val_accuracy: 0.9040
Epoch 6/100
375/375 [==============================] - 2s 5ms/step - loss: 0.2518 - accuracy: 0.8996 - val_loss: 0.2919 - val_accuracy: 0.8810
Epoch 7/100
375/375 [==============================] - 2s 5ms/step - loss: 0.2255 - accuracy: 0.9131 - val_loss: 0.2667 - val_accuracy: 0.8960

In [29]:
model.save('./angle_classifying_model.h5')

In [30]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 5, 128)            68096     
                                                                 
 dropout (Dropout)           (None, 5, 128)            0         
                                                                 
 lstm_1 (LSTM)               (None, 128)               131584    
                                                                 
 dropout_1 (Dropout)         (None, 128)               0         
                                                                 
 dense (Dense)               (None, 64)                8256      
                                                                 
 dense_1 (Dense)             (None, 3)                 195       
                                                                 
Total params: 208,131
Trainable params: 208,131
Non-trai

In [1]:
model.load('./angle_classifying_model.h5')

NameError: name 'model' is not defined